version: '3.8'

services:
  web:
    build:
      context: .
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgresql-tech-books-circle.cdgcy8cgi68g.us-west-2.rds.amazonaws.com
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: arn:aws:secretsmanager:us-west-2:445162103134:secret:rds!db-b4ca9117-b5f9-4deb-bfb2-2edfbfea6dcf-cNRR7Z
    depends_on: [] 
